
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://bepzfsuuppxuevpvpffh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlcHpmc3V1cHB4dWV2cHZwZmZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Mjc1OTYsImV4cCI6MjA2NTUwMzU5Nn0.uwM9hddDV5TCGabyXqqHChCGTgma4Of6FaOvgFr98Ds";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
